r=int(input("radius of the circle:"))
l=int(input("length of thr rectangle:"))
b=int(input("breadth of the rectangle:"))
base=int(input("base of the triangle:"))
h=int(input("height of the triangle:"))
circle=3.14*r*r
rectangle=l*b
triangle=0.5*base*h
print("area of circle=",circle)
print("area of rectangle=",rectangle)
print("area of triangle=",triangle)
